### PR TITLE
Large files have negative available bytes due to long to int type cas…

### PR DESCRIPTION
**Pull request by davydotcom**
…ting..

### CODE REVIEW

**Comment by davydotcom** [comment]
It was observed that NFSFileInputStream was coming back with 0 bytes if file was larger than 2.1GB (basically Integer.MAX_VALUE)

**Comment by davydotcom** [comment]
-1 implies end of stream. The use of this field is being used improperly as it is right now. Available is not meant to show the amount of bytes remaining in the file but rather the amount available to fetch from the stream without blocking (is the proper use case). Since it is being used to imitate this for pulling the chunked bytes it seemed better suited to imply that there are bytes available for now as total file size here is not at all a valid dataset . The interface is not the problem

**Comment by davydotcom** [comment]
The proper answer or definition of the available() method from the javadoc is this...

"
Returns an estimate of the number of bytes that can be read (or skipped over) from this input stream without blocking by the next invocation of a method for this input stream. The next invocation might be the same thread or another thread. A single read or skip of this many bytes will not block, but may read or skip fewer bytes. "

So if implementing properly it would estimate this value and never be based on the size of the file itself.

**Comment by davydotcom** [comment]
I should highlight this is a minimal fix so that it behaves acceptably with other streams for fetching files larger than 1.2GB (in our case its QCOW2 , RAW , or VMDK image files for backup/recovery)

**Comment by DavidASeibert** [comment]
Yes, my initial thoughts were a bit off. Coming back here from other code...

`-1` does not imply `EOF` for `available()`, but `0` does according to the javadoc. Probably the best estimate the code can give is the following:

`bytesLeftInBuffer()` if that is > 0, or
`0` if `_isEof`, or
`_bytesInBuffer` otherwise.

That will give either the remaining bytes that can be read without going to the NFS file, or the best estimate of what the next NFS read will give if the buffer is currently empty and there is still data left to read. That will also give good processing results, as the buffer size is typically set to the optimum NFS read size for that system. Does that make sense to you?

**Comment by davydotcom** [comment]
Yes it does. -1 is actually used a lot on HTTP InputStreams in their docs to imply EOF because 0 doesnt mean the stream is at end of file. It means the transfer might be hung and theres nothing to be read at this moment but there may be shortly.

**Comment by DavidASeibert** [comment]
The javadoc says that `0` means you are at the end of the stream. Yes, there may be extensions for subclasses that have special values for `-1`, but that doesn't really make sense for anything other than special devices, and we're trying to stay as plain vanilla as possible.

https://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html#available()

**Comment by davydotcom** [comment]
Im reading the java doc and see nothing of the sort. As a matter of fact on the base implementation "The available method for class InputStream always returns 0.
“

It says it will return an ESTIMATE of the bytes available for reading or it will return 0 when it reaches the end of the stream. 0 could also be an estimate of bytes available for being read without blocking

**Review by DavidASeibert — APPROVED** [review]
Approving, although the solution will likely need tweaking before the next release.

**Comment by twincitiesguy** [comment]
I'm leaving this comment here, even though this PR has already been merged, because we are trying to get a release out that includes a debug fix (#42).  Seems to me, based on the method contract, `available()` should just return `bytesLeftInBuffer()`.  The intent is to reveal how many bytes can be read without any (blocking) network IO, and I think `bytesLeftInBuffer()` should provide this accurately, unless I'm missing something.  FYI, we may introduce this change prior to the next release.

**Pull request merged**
